url: "https://guilhermeivo.github.io"
baseurl: ""
title: "guilhermeivo"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll/webpack

webpack:
  only_in:
    - _site
  cleanup_files:
    - src
    - node_modules
    - webpack.config.js
    - package.json
    - package-lock.json

exclude: 
  - test/
  - dependencies/
  - bin/
  - LICENSE
  - README.md